### ISSUE TITLE
Shortcomings of the new cmake test framework

### ISSUE THREAD

**Issue by mihaipopescu** [uncrustify/uncrustify#977]
I wanted to collect all the issues of the new cmake test framework in comparison with the old `run_tests.py`:
- [ ] bug: .test parser regex doesn't support tabs (https://github.com/uncrustify/uncrustify/issues/854#issuecomment-265780826)
- [ ] ability to iterate on .test files (add/remove tests) without regenerating the cache (see #972)
- [ ] ability to run a specified suite (can be outside of the default batch of suites) (see #976)
- [ ] ability to show diffs on failures (-d option)
- [ ] ability to generate debug logs/files (-g option)
- [ ] ability to filter tests range (-r option)
- [ ] ability to use another result folder (--results option, useful when comparing result of two builds)

**Comment by CDanU** [comment]
It is not comfortable to put in actual ranges, but it is still possible to narrow down tests that should run.

CTest has this options:
```
-L <regex>, --label-regex <regex>
    Run tests with labels matching regular expression.

    This option tells ctest to run only the tests whose labels match the given regular expression.

-LE <regex>, --label-exclude <regex>
    Exclude tests with labels matching regular expression.

    This option tells ctest to NOT run the tests whose labels match the given regular expression.

-R <regex>, --tests-regex <regex>
    Run tests matching regular expression.

    This option tells ctest to run only the tests whose names match the given regular expression.

-E <regex>, --exclude-regex <regex>
    Exclude tests matching regular expression.

    This option tells ctest to NOT run the tests whose names match the given regular expression.
```

Run only only the cpp tests
`ctest -j 8 --output-on-failure -R "^cpp_"`

Ranges:
`ctest -j 8 --output-on-failure -R "_(000[0-9]+|025[0-9]+)"`

`ctest` can be run directly in the build directory.

**Comment by mwoehlke-kitware** [comment]
I'm late to the party here, but now that I'm looking at the various ways the tests are executed, I think it would make sense to consolidate `run_tests.py` and the CTest tests. Specifically, since we require Python anyway, I think it might make sense to split `run_tests.py` into two files; one to parse the tests, and one to actually run a single test. The latter should be able to be run stand-alone with appropriate arguments, or `import`ed into the former. The former could then be reworked to have two modes; one to just run the tests, and one to emit CTest script to set up the tests for CTest. This would also allow us to eliminate `run_test.cmake` and most of the logic in `tests/CMakeLists.txt`, giving us one and only one way of both parsing the test lists, and actually executing the tests, just with different front-ends for invoking these operations. This would solve the first two items. Items three and five I believe are already solved by features of CTest, and item four is solved by #1799.

On a related note, I think it would make sense to write the test results to the build directory instead of the source directory; I believe this would solve the last item on the list.

**Comment by mihaipopescu** [comment]
> On a related note, I think it would make sense to write the test results to the build directory instead of the source directory;

**Comment by mihaipopescu** [comment]
@mwoehlke-kitware I don't fully understand your proposal. 

Are you saying to move the entry point of the test runner back to `run_tests.py` and that one, could call `ctest` where it makes sense?

**Comment by mwoehlke-kitware** [comment]
The other way around... I would move running of *a* test from `run_tests.py` (D) to a new `run_test.py` (T), which would be set up to either run stand-alone (to run one test) or to have (a) function(s) that `run_tests.py` (D) would import. CTest would call `run_test.py` (T) in place of `run_test.cmake`; they would do basically the same things.

...and I would also add a mode to `run_tests.py` (D) that would generate a CTest script with the set of tests, which would replace much of the logic currently in `tests/CMakeLists.txt`. The existing functions of `run_tests.py` (D) would be retained, but the overhead would be just a front-end over shared logic.

(D=Driver, T=Task, to help tell them apart given the file names differ only by one character.)
